name: Build, Push and Deploy to Kubernetes

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Determine Docker tag
        id: docker_tag
        run: |
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            echo "tag=latest" >> $GITHUB_ENV
          else
            echo "tag=${GITHUB_REF##*/}" >> $GITHUB_ENV
          fi

      - name: Build Docker image
        run: |
          sudo docker build . -t spencer98/netology-diploma-site:${{ env.tag }}

      - name: Push Docker image
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | sudo docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          sudo docker push spencer98/netology-diploma-site:${{ env.tag }}

      - name: Set up Kubernetes context
        run: |
          echo "${{ secrets.KUBE_CONFIG }}" > kubeconfig
          export KUBECONFIG=$(pwd)/kubeconfig

      - name: Deploy to Kubernetes
        run: |
          sudo kubectl set image deployment/diplom-app netology-diploma-site=spencer98/netology-diploma-site:${{ env.tag }} -n diploma-site
          sudo kubectl rollout status deployment/diplom-app -n diploma-site
