name: Build and Deploy to Kubernetes

on:
  push:
    branches:
      - main  # Запускать при каждом коммите в ветку main

jobs:
  build:
    runs-on: self-hosted  # Использовать self-hosted агент

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          sudo docker build . -t spencer98/netology-diploma-site:latest

      - name: Push Docker image
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          sudo docker push spencer98/netology-diploma-site:latest

      - name: Set up Kubernetes context
        run: |
          echo "${{ secrets.KUBE_CONFIG }}" > kubeconfig
          export KUBECONFIG=$(pwd)/kubeconfig

      - name: Deploy to Kubernetes
        run: |
          sudo kubectl set image deployment/diplom-app netology-diploma-site=spencer98/netology-diploma-site:latest -n diploma-site
          sudo kubectl rollout status deployment/diplom-app -n diploma-site
